"""Rebuild the reader-mode text copy inside wordpress-embed-snippet.html.

Reader modes extract from the POST's dom and never look inside an iframe, so
with only the embed in the post there is no article for them to find. This
lifts the story's prose into the post, between the markers in the snippet.

Run after editing the story's copy:  python3 _gen-reader-copy.py
"""
import re, pathlib

story = pathlib.Path("senior-story.html").read_text()
body = story.split('<div class="continues">', 1)[1].rsplit("</div>", 1)[0]

# every block of running copy, in the order it appears
blocks = re.findall(r'<(h2|p|figcaption)\b([^>]*)>(.*?)</\1>', body, re.S)

out = []
for tag, attrs, inner in blocks:
    inner = re.sub(r'\s+', ' ', inner).strip()
    if not inner:
        continue
    inner = re.sub(r'\sclass="[^"]*"', '', inner)      # presentational hooks
    inner = re.sub(r'\sstyle="[^"]*"', '', inner)
    if tag == "figcaption":
        out.append(f"<p><em>{inner}</em></p>")          # photo caption
    elif tag == "h2":
        # No id: nothing links here (the real anchors are in the story
        # itself), and Readability scores a heading's id against its
        # "negative" pattern and drops the heading if it loses -- which is
        # exactly what happened to the "Neighbors who close the last mile"
        # subhead while these carried ids.
        out.append(f"<h2>{inner}</h2>")
    else:
        out.append(f"<p>{inner}</p>")

copy = "\n  ".join(out)
block = f'''<!-- READER COPY START (generated by _gen-reader-copy.py -- do not hand-edit) -->
<div class="ss-reader-copy">
  {copy}
</div>
<!-- READER COPY END -->'''

snip = pathlib.Path("wordpress-embed-snippet.html")
text = snip.read_text()
pat = re.compile(r'<!-- READER COPY START.*?<!-- READER COPY END -->', re.S)
if pat.search(text):
    text = pat.sub(block, text)
else:
    text = text.replace('</div>\n\n<script src="https://pym.nprapps.org',
                        '</div>\n\n' + block + '\n\n<script src="https://pym.nprapps.org')
snip.write_text(text)
words = len(re.sub(r"<[^>]+>", " ", copy).split())
print(f"{len(out)} blocks, ~{words} words")
